version: "3.7"
services:
  node_a:
    image: cdcf:latest
    environment:
      HOST: node_a
      SEEDS: node_a:4445,node_b:4445
      APP: /bin/cluster
    ports:
      - 50051:50051
      - 3335:3335
    networks:
      - cdcf
  node_b:
    image: cdcf:latest
    environment:
      HOST: node_b
      SEEDS: node_a:4445,node_b:4445
      APP: /bin/cluster
    ports:
      - 50052:50051
    networks:
      - cdcf
  node_c:
    image: cdcf:latest
    environment:
      HOST: node_c
      SEEDS: node_a:4445,node_b:4445
      APP: /bin/cluster
    ports:
      - 50053:50051
    networks:
      - cdcf
networks:
  cdcf: