---
- name: Update git
  tasks:
    - git:
      repo: 'https://github.com/thoughtworks-hpc/cdcf.git'
      dest: /home/twer/
      update: yes
      version: yanghui_cluster_mod

- name: Copy docker compose file to nodes
  hosts: all
  tasks:
    - name: actual copying
      copy:
        src: /home/twer/cdcf/docker/yanghui_cluster_test_env.yml
        dest: /home/twer/cdcf/docker/yanghui_cluster_test_env.yml

- name: Run docker compose
  hosts: server
  become: true
  tasks:
    - name: Run docker compose on server
      docker_compose:
        project_src: /home/twer/cdcf/docker/
        files: yanghui_cluster_test_env.yml
        services: yanghui_root_v2
        state: present
- name: Run docker compose
  hosts: worker
  become: true
  tasks:
    - name: Run docker compose on worker
      docker_compose:
        project_src: /home/twer/cdcf/docker/
        files: yanghui_cluster_test_env.yml
        services: yanghui_worker1_v2
        state: present
- name: Run docker compose
  hosts: client
  become: true
  tasks:
    - name: Run docker compose on client
      docker_compose:
        project_src: /home/twer/cdcf/docker/
        files: yanghui_cluster_test_env.yml
        services: yanghui_client
        state: present