name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v1
      - name: Install conan && conan package tools
        run: |
          python -m pip install --upgrade pip
          pip install conan
          pip install conan_package_tools
      - uses: actions/checkout@v1
      - name: conan
        run: |
          pwd
          conan remote add inexorgame "https://api.bintray.com/conan/inexorgame/inexor-conan"
          conan install .  --build missing
          ls
      - name: cmake
        env:
          ACTOR_SYS_ONLY: 1
        run: |
          pwd
          ls
          cmake -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake -G "Visual Studio 16 2019" .

